### ISSUE TITLE
RabbitMQ.Client new version (3.4.0)

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#45]
The current Chinchilla nugget package contains the 3.1.x version of RabbitMQ.Client. There is a new version of RabbitMQ.Client (version 3.4). Is the current Chincilla support the new version of RabbitMQ.Client.

**Comment by jonnii** [comment]
@alana1 i believe the pre-release package has RabbitMq.Client Version 3.3.2. I can look into what's involved with upgrading to 3.4.

**Comment by jonnii** [comment]
@alana1 I remember I already have a PR open for this: https://github.com/jonnii/chinchilla/pull/44

will get it merged and cut a new release.

**Comment by jonnii** [comment]
@alana1 publishing now.

**Comment by alana1** [comment]
Thank you jonni for your quick response.

**Comment by alana1** [comment]
I wanted to know if the change you made is available in nugget to reflect the new version of RabbitMQ.Client. I tried installing the Chinchilla nugget package is it still referencing the old version from the nugget package.

**Comment by jonnii** [comment]
should just be able to do an `update-package chinchilla` and you'll be good.

The dependency is > 3.4 (http://www.nuget.org/packages/chinchilla).
