### ISSUE TITLE
Receive disconnect event if RabbitMQ Server is stopped or client lost network connectivity

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#46]
Is there a way to handle an event or capture within Chinchilla should the RabbitMQ server is stopped or client lost connectivity?

Thanks,

Alan

**Comment by jonnii** [comment]
what's your use case?

**Comment by alana1** [comment]
Use case be where the client is connected to RabbitMQ Server via Chinchilla. While connected, the RabbitMQ server is stopped/restart or the client lost network connectivity, I would like to receive some type of 'disconnected' event such that the client application will attempt to reconnect or perform some type of action.

**Comment by jonnii** [comment]
There's no easy way to do this I don't think. The closet thing I can think of doing is having some way of making your own model factory and listening to reconnections on the model. However IIRC the new version of the rabbitmq client will automatically retry, maybe they have a hook we should be using?

Take a look at:

https://github.com/jonnii/chinchilla/blob/master/src/Chinchilla/DefaultConnectionFactory.cs#L135
https://github.com/jonnii/chinchilla/blob/master/src/Chinchilla/ModelFactory.cs#L36

just so you know if chinchilla gets disconnected somehow it will try to reconnect.

**Comment by alana1** [comment]
Thank you for your help.
