### ISSUE TITLE
TaskDeliveryStrategy number of workers

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#47]
Hi Jonathan,

If I don't supply NumWorkers property a value, what is the default number of workers to handle messages in TaskDeliveryStrategy? Should I set NumWorkers and what is the ideal number?

Thank you for your help.

Alan

**Comment by jonnii** [comment]
TaskDeliveryStrategy just uses the TPL, the number of workers represents the number of active deliveries. That will scale with the TPL. 

If you want to limit the number of threads you can use the `WorkerPoolDeliveryStrategy`, which by default will have 1 worker.

Does that help?

**Comment by alana1** [comment]
Makes sense. Thank you for your response.
