### ISSUE TITLE
Frequent Invocation of CreatePublisher

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#48]
Hello Jonathan,

I have an application where multiple users using. I have one exchange (topic) and one queue. Each consumer connects to that one exchange and queue with unique binding for each consumer. I have this application that is a publisher it publishes message to that one exchange and queue. This application establishes one single IBUS which establish one connection. Each message publish, the application invokes the 'CreatePublisher' (IPublisher) and then invokes the 'Publish' method. My question is, should I only invoke 'CreatePublisher' once, maintain that throughout the life of the application and simply invoke Publish method each time to publish a message?

I appreciate your feedback.

Thanks,

Alan

**Comment by jonnii** [comment]
The idea of an IPublisher is that it should be reused. You should keep it around as long as you need it as dispose of it when you're done, this will then clean up any connections associated.
