### ISSUE TITLE
How to implement message TTL to queue or per message

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#49]
Hi Jon,

Is there way to implement message TTL to queue or per message? If for queue, is this done when creating topology builder.

Thanks,

Alan

**Comment by jonnii** [comment]
I think you can add `IHasTimeOut` on the messages or do it with a custom topology builder.

**Comment by alana1** [comment]
I know how to implement IHasTimeOut on the message. Do you have sample for custom topology builder that sets the message timeout?

**Comment by jonnii** [comment]
@alana1 i don't know if that's do-able, but I would happily accept a PR for it. it would be a method on publisher configuration I think.

**Comment by alana1** [comment]
Hi Jon, I created PR #50
