### ISSUE TITLE
Is there a way to determine if the connection is still opened

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#51]
I would like to know if there is a way to check if the connection to RabbitMQ server is still connected. I know in ModelFactory there is IsOpen property. However, is not available in IBus interface. Is there a way to check IsOpen or similar to and verify the connectivity is still up?

Thanks,

Alan

**Comment by jonnii** [comment]
for publishing or subscribing?

**Comment by alana1** [comment]
for both.

**Comment by jonnii** [comment]
For subscribers you have `IsStarted` and also the ability to get the state of the subscription, which will show you delivery queue state (these map to models). For publishers you can get access to the `IModelReference` which could be changed to have a state property on it, however right now it's assumed that if the publisher exists then it's "connected".
