### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#52]
Hi Jonni,

Is there a way to check rabbitMQ connectivity. For example, if I create a IBus variable and successfully connect to RabbitMQ, few minutes later, the connectivity between client PC and RabbitMQ is disconnected, how I get knowledge that the connection has been disconnected?

Thank you,

Alan

**Comment by jonnii** [comment]
@alana1 most common reason i've seen for this is a load balancer which times out the connection. rabbitmq has a heartbeat which should keep the connection active, but the default is 5 mins (i think), so you need to have a tcp timeout on your load balancer which is higher than this or lower the heartbeat time. 

if it's a chinchilla thing you can try enabling logs and see if anything shows up. 

there might also be a way to get diagnostics from rabbitmq management client, but I've never had to do that.
