### ISSUE TITLE
RabbitMQ client version 3.4.4 compatibility

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#53]
Hello, is Chinchilla version compatible with RabbitMQ client version 3.4.4?

**Comment by jonnii** [comment]
I'll upgrade the client version.

**Comment by jonnii** [comment]
@alana1 there is no `3.4.4`, but there is a `3.4.3`, I've updated the project references. you shouldn't have to upgrade as nuget should bring in any version that is `3.4.*`, but you can if you want.

**Comment by alana1** [comment]
3.4.4 was released on 2/11/2015 (http://www.rabbitmq.com/releases/rabbitmq-dotnet-client/v3.4.4/)

**Comment by jonnii** [comment]
Ah, well it's not in nuget yet (http://www.nuget.org/packages/RabbitMQ.Client/), so no way to consume it. Once it's released I can update again.
