### ISSUE TITLE
Chincilla generating exception when using RabbitMQ client version 3.5

### ISSUE THREAD

**Issue by alana1** [jonnii/chinchilla#58]
Hello,

When using current version of Chinchilla and update the RabbitMQ client to version 3.5, the following exception is generated when invoking Depo.Connect.

Could not load type 'RabbitMQ.Client.Events.ConnectionShutdownEventHandler' from assembly 'RabbitMQ.Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce'.

Thanks,

Alan

**Comment by jonnii** [comment]
Chinchilla doesn't yet work with 3.5, can you submit a PR updating it?

**Comment by mrbedo** [comment]
Same bug

**Comment by jonnii** [comment]
@mrbedo dont worry the open source fairies are here for you.

**Comment by mrbedo** [comment]
:princess:
