### ISSUE TITLE
Prefetch count issue

### ISSUE THREAD

**Issue by thingylab** [jonnii/chinchilla#64]
`ISubscriptionBuilder.WithPrefetchCount` does not seem to have any effect.

For instance, after opening this subscription:
```csharp
var subscription = _subscribingBus.Subscribe<RoutingKeyMessage<string>>(
                OnMsgReceive,
                b => b.WithPrefetchCount(1));
```
the queue still has the default prefetch count of 50.

I'll take a look and open a PR.

**Comment by jonnii** [comment]
@thingylab yeah that's weird.

**Comment by jonnii** [comment]
@thingylab works in the sample?

**Comment by thingylab** [comment]
@jonnii yeah, the code we're running is slightly different, I trying to find where this is failing to set the fetch count.
