### ISSUE TITLE
Send/Receive pattern

### ISSUE THREAD

**Issue by abrasat** [jonnii/chinchilla#66]
Hello,
Is it possible to implement the send/receive pattern with the available chinichilla bus interface ? We need this pattern for instance in a client/server scenario, where different clients send data to a well-known queue on a server application (several sender and one receiver).
Thanks in advance.

**Comment by jonnii** [comment]
It is yes, see below.

https://github.com/jonnii/chinchilla#request-response

https://github.com/jonnii/chinchilla/blob/master/src/Chinchilla.Integration/Features/RequestResponseFeature.cs

**Comment by abrasat** [comment]
Can you please detail about how to use request/reply to implement send/receive?
If I understand the link above, the "sender" application should send a message as request/reply, is that correct ? Is there any possibility to disable the response, if none is expected ?
And what about the "receiver" application: does the "receiver" subscribe to a message, in view to receive it ? Or how else should the "receiver" be implemented ?

**Comment by jonnii** [comment]
I think you need to spend some time understanding RabbitMQ fundamentals so you can understand how you would implement RPC without the need for a library. Once you understand that then there should be more than enough examples in the integration tests for you to get started with.
