### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by cocowalla** [jonnii/chinchilla#82]
It would be nice to support .NET Standard as well as .NET Framework, so Chinchilla would run on .NET Core.

I've ran the [Portability Advisor](https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a8a6-e56c7905292b) on the Chinchilla assembly, and the only issue was with `DefaultMessageTypeFactory`, which does some stuff with reflection and app domains that is no longer supported in .NET Standard.

I would do this, but I've been away from Chinchilla for quite a while, and am not very familiar with the code base any more. And looking at `DefaultMessageTypeFactory` it's rather difficult for me to decipher what it's doing :)

**Comment by jonnii** [comment]
Heyo! Welcome back! I would also like to get this working with core, but haven't yet had the time to figure it all out. I'm personally waiting for the visual studio tooling to be a bit better as hopefully it'll come with an automated way of porting a project to core. Have you ported a project before? I'd be happy to figure out a better way to get `DefaultMessageTypeFactory` working (maybe using expression trees?) if that would help. I'm just not exactly sure where to start with porting a project to core....

**Comment by cocowalla** [comment]
I have ported a couple of projects, using [this](https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/) and [this](http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/) as guides - it was surprisingly painless. An alternative approach in `DefaultMessageTypeFactory` would certainly help :)

**Comment by jonnii** [comment]
@cocowalla so what the default message type factory does is generate an implementation of an interface so you can _subscribe_ to an interface, and not to an implementation. This can be useful for messaging versioning. I'm sure something similar is possible in core, I'll give it a whirl.

**Comment by jonnii** [comment]
@cocowalla i'm going to close this, we have a net standard build now.
